import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenHeader } from "../components/ScreenHeader";
import { deliver, dispute, loadActivity, loadTransaction, payWallet, readNotification, receive, sendMessage, submitEvidence, type ActivityKind, type ActivityRow, type TransactionDetail } from "../lib/activity";
import type { MobileAccount } from "../lib/auth";
import { colors } from "../theme";

const kinds: ActivityKind[] = ["bids", "orders", "notifications", "disputes"];
const money = (value?: number) => value?.toLocaleString("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });

export function ActivityScreen({ account, onRequireAuth }: { account: MobileAccount | null; onRequireAuth: () => void }) {
  const [kind, setKind] = useState<ActivityKind>("orders"); const [rows, setRows] = useState<ActivityRow[]>([]); const [selected, setSelected] = useState<TransactionDetail | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [reload, setReload] = useState(0);
  useEffect(() => { if (!account) return; let current = true; const timer = setTimeout(() => { setLoading(true); setError(null); loadActivity(kind).then((data) => { if (current) setRows(data); }).catch((e) => { if (current) setError(e instanceof Error ? e.message : "Could not load activity."); }).finally(() => { if (current) setLoading(false); }); }, 0); return () => { current = false; clearTimeout(timer); }; }, [account, kind, reload]);
  async function open(row: ActivityRow) { if (kind === "notifications") { await readNotification(row.id); setReload((x) => x + 1); } else if (kind !== "bids") setSelected(await loadTransaction(row.id)); }
  async function act(name: "pay" | "deliver" | "receive" | "dispute" | "message") { if (!selected) return; setLoading(true); setError(null); try { if (name === "pay") await payWallet(selected.id); else if (name === "deliver") await deliver(selected.id); else if (name === "receive") await receive(selected.id); else if (name === "dispute") await dispute(selected.id); else { await sendMessage(selected.id, message); setMessage(""); } setSelected(await loadTransaction(selected.id)); setReload((x) => x + 1); } catch (e) { setError(e instanceof Error ? e.message : "Could not update transaction."); } finally { setLoading(false); } }
  if (!account) return <ScrollView style={s.screen} contentContainerStyle={s.content}><ScreenHeader title="Activity" subtitle="Bids, orders, escrow, notifications, and disputes." /><Text style={s.empty}>Sign in to load protected Hazi activity.</Text><Button label="Sign in" onPress={onRequireAuth} /></ScrollView>;
  if (selected) return <ScrollView style={s.screen} contentContainerStyle={s.content}><ScreenHeader title={selected.title} subtitle={`${selected.detail} · ${money(selected.amount)}`} onBack={() => setSelected(null)} />{error ? <Text style={s.error}>{error}</Text> : null}<View style={s.summary}><Text style={s.status}>{selected.status.replaceAll("_", " ")}</Text><Text style={s.copy}>Funds stay protected until receipt, release, refund, or dispute resolution.</Text></View>{selected.isBuyer && selected.status === "escrow_pending" ? <Button label="Pay from wallet" onPress={() => void act("pay")} /> : null}{selected.isSeller && selected.status === "paid" && !selected.sellerDeliveryStartedAt ? <Button label="Mark item on the way" onPress={() => void act("deliver")} /> : null}{selected.isBuyer && selected.status === "paid" ? <Button label="Confirm receipt and release" onPress={() => void act("receive")} /> : null}{["escrow_pending", "paid"].includes(selected.status) ? <Button label="Open dispute" onPress={() => Alert.alert("Open dispute?", "This pauses the normal escrow flow for Hazi review.", [{ text: "Cancel" }, { text: "Open", style: "destructive", onPress: () => void act("dispute") }])} /> : null}{selected.status === "disputed" ? <EvidenceForm transactionId={selected.id} onError={setError} /> : null}<Text style={s.heading}>Escrow chat</Text>{selected.messages.map((x) => <View key={x.id} style={[s.message, x.senderId === account.user.id && s.mine]}><Text style={s.rowTitle}>{x.senderId === account.user.id ? "You" : "Other party"}</Text><Text style={s.copy}>{x.body}</Text></View>)}<TextInput value={message} onChangeText={setMessage} multiline placeholder="Coordinate pickup, delivery, or receipt" placeholderTextColor={colors.muted} style={s.input} /><Button label="Send message" onPress={() => void act("message")} />{loading ? <ActivityIndicator color={colors.success} /> : null}</ScrollView>;
  return <ScrollView style={s.screen} contentContainerStyle={s.content}><ScreenHeader title="Activity" subtitle="Live protected Hazi account activity." /><ScrollView horizontal contentContainerStyle={s.tabs}>{kinds.map((x) => <Pressable key={x} style={[s.tab, kind === x && s.tabOn]} onPress={() => setKind(x)}><Text style={[s.tabText, kind === x && s.tabTextOn]}>{x}</Text></Pressable>)}</ScrollView>{error ? <Text style={s.error}>{error}</Text> : null}{loading ? <ActivityIndicator color={colors.success} /> : null}<View style={s.list}>{rows.map((x) => <Pressable key={x.id} style={s.row} onPress={() => void open(x)}><View style={s.flex}><Text style={s.rowTitle}>{x.title}</Text><Text style={s.copy}>{x.detail}</Text></View>{x.amount ? <Text style={s.amount}>{money(x.amount)}</Text> : null}<Text style={s.badge}>{x.status.replaceAll("_", " ")}</Text></Pressable>)}{!loading && !rows.length ? <Text style={s.empty}>No {kind} yet.</Text> : null}</View></ScrollView>;
}
function Button({ label, onPress }: { label: string; onPress: () => void }) { return <Pressable style={s.button} onPress={onPress}><Text style={s.buttonText}>{label}</Text></Pressable>; }
function EvidenceForm({ transactionId, onError }: { transactionId: string; onError: (message: string | null) => void }) { const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false); async function save() { setSaving(true); setSaved(false); onError(null); try { await submitEvidence(transactionId, notes); setNotes(""); setSaved(true); } catch (e) { onError(e instanceof Error ? e.message : "Could not submit evidence."); } finally { setSaving(false); } } return <View style={s.summary}><Text style={s.heading}>Add dispute evidence</Text><Text style={s.copy}>Record facts, dates, delivery details, or other information for Hazi review.</Text><TextInput value={notes} onChangeText={setNotes} multiline placeholder="Evidence note" placeholderTextColor={colors.muted} style={s.input} />{saved ? <Text style={s.badge}>Evidence submitted</Text> : null}<Button label={saving ? "Submitting…" : "Submit evidence"} onPress={() => void save()} /></View>; }
const s = StyleSheet.create({ screen: { flex: 1 }, content: { padding: 18, paddingBottom: 38, gap: 12 }, flex: { flex: 1 }, tabs: { gap: 8 }, tab: { borderWidth: 1, borderColor: colors.border, borderRadius: 999, paddingHorizontal: 15, paddingVertical: 10 }, tabOn: { backgroundColor: colors.primary, borderColor: colors.success }, tabText: { color: colors.muted, textTransform: "capitalize", fontWeight: "800" }, tabTextOn: { color: colors.white }, list: { gap: 9 }, row: { flexDirection: "row", alignItems: "center", gap: 9, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, borderRadius: 17, padding: 14 }, rowTitle: { color: colors.text, fontWeight: "900", fontSize: 13 }, copy: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 3 }, amount: { color: colors.text, fontWeight: "900", fontSize: 11 }, badge: { color: colors.success, fontSize: 9, fontWeight: "800", textTransform: "capitalize" }, empty: { color: colors.muted, textAlign: "center", padding: 24 }, error: { color: "#ffaaa1", backgroundColor: "#3d2021", borderRadius: 14, padding: 13 }, summary: { backgroundColor: colors.surfaceRaised, borderRadius: 18, padding: 17, gap: 10 }, status: { color: colors.text, fontWeight: "900", fontSize: 22, textTransform: "capitalize" }, button: { minHeight: 49, backgroundColor: colors.primary, borderRadius: 15, alignItems: "center", justifyContent: "center" }, buttonText: { color: colors.white, fontWeight: "900" }, heading: { color: colors.text, fontSize: 18, fontWeight: "900" }, message: { alignSelf: "flex-start", maxWidth: "85%", backgroundColor: colors.surfaceRaised, borderRadius: 15, padding: 12 }, mine: { alignSelf: "flex-end", backgroundColor: colors.primarySoft }, input: { minHeight: 80, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceRaised, color: colors.text, borderRadius: 16, padding: 13, textAlignVertical: "top" } });
