import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ScreenHeader } from "../components/ScreenHeader";
import type { MobileAccount } from "../lib/auth";
import { loadEditableProfile, saveEditableProfile, type EditableProfile } from "../lib/profile";
import { colors } from "../theme";
import type { AccountSection } from "./AccountSectionScreen";

const menu = [
  ["shield-checkmark-outline", "Verification", "Identity, phone, and liveness checks", "verification"], ["wallet-outline", "Wallet", "Balance, funding, escrow, and refunds", "wallet"], ["card-outline", "Payout settings", "Verified settlement account", "payouts"], ["list-outline", "My listings", "Draft, active, accepted, and closed auctions", "listings"], ["people-outline", "Agent workspace", "Requests and assigned client sales", "agent"], ["help-circle-outline", "Support", "Reports, disputes, and marketplace help", "support"]
] as const;

export function ProfileScreen({ account, onRequireAuth, onSignOut, onOpenSection, onProfileSaved }: { account: MobileAccount | null; onRequireAuth: () => void; onSignOut: () => Promise<void>; onOpenSection: (section: AccountSection) => void; onProfileSaved: () => Promise<void> }) {
  const [editing, setEditing] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [profile, setProfile] = useState<EditableProfile | null>(null);
  async function openEditor() { setLoading(true); setError(null); try { setProfile(await loadEditableProfile()); setEditing(true); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not load your profile."); } finally { setLoading(false); } }
  async function save() { if (!profile) return; setLoading(true); setError(null); try { await saveEditableProfile(profile); await onProfileSaved(); setEditing(false); Alert.alert("Profile saved", "Your Hazi contact and public profile details are up to date."); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not save your profile."); } finally { setLoading(false); } }
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <ScreenHeader title="Your Hazi account" subtitle="Trust, payments, listings, and support." />
    <View style={styles.accountCard}><View style={styles.avatar}><Ionicons name="person" size={32} color={colors.text} /></View><View style={styles.flex}><Text style={styles.guest}>{account?.fullName ?? "Guest account"}</Text><Text style={styles.guestCopy}>{account ? `${account.role} · ${account.verificationStatus}` : "Sign in to load your verified Hazi profile and role."}</Text></View></View>
    {error ? <Text style={styles.error}>{error}</Text> : null}
    {account ? <Pressable style={styles.editButton} disabled={loading} onPress={() => void openEditor()}>{loading && !editing ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>Edit profile</Text>}</Pressable> : null}
    {editing && profile ? <View style={styles.form}><Text style={styles.formTitle}>Profile details</Text><Field placeholder="Full name" value={profile.fullName} set={(fullName) => setProfile({ ...profile, fullName })} /><Field placeholder="Company name (optional)" value={profile.companyName} set={(companyName) => setProfile({ ...profile, companyName })} /><Field placeholder="Phone number" value={profile.phone} set={(phone) => setProfile({ ...profile, phone })} keyboardType="phone-pad" /><Field placeholder="Location" value={profile.location} set={(location) => setProfile({ ...profile, location })} /><Field placeholder="Avatar URL (optional)" value={profile.avatarUrl} set={(avatarUrl) => setProfile({ ...profile, avatarUrl })} keyboardType="url" /><View style={styles.actions}><Pressable style={styles.cancelButton} onPress={() => setEditing(false)}><Text style={styles.primaryText}>Cancel</Text></Pressable><Pressable style={styles.saveButton} disabled={loading} onPress={() => void save()}>{loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>Save profile</Text>}</Pressable></View></View> : null}
    <Pressable style={styles.primaryButton} onPress={account ? () => void onSignOut() : onRequireAuth}><Text style={styles.primaryText}>{account ? "Sign out" : "Sign in or create account"}</Text></Pressable>
    <Text style={styles.sectionTitle}>Account services</Text><View style={styles.menu}>{menu.map(([icon, title, copy, section]) => <Pressable key={section} accessibilityRole="button" accessibilityLabel={title} style={styles.menuItem} onPress={() => onOpenSection(section)}><View style={styles.menuIcon}><Ionicons name={icon} size={21} color={colors.success} /></View><View style={styles.flex}><Text style={styles.menuTitle}>{title}</Text><Text style={styles.menuCopy}>{copy}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></Pressable>)}</View>
    <View style={styles.trustNote}><Ionicons name="lock-closed" size={18} color={colors.success} /><Text style={styles.trustText}>Roles and permissions are loaded from trusted Hazi profile data—not editable account metadata.</Text></View>
  </ScrollView>;
}

function Field({ placeholder, value, set, keyboardType = "default" }: { placeholder: string; value: string; set: (value: string) => void; keyboardType?: "default" | "phone-pad" | "url" }) { return <TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType={keyboardType} autoCapitalize={keyboardType === "url" ? "none" : "sentences"} style={styles.input} />; }

const styles = StyleSheet.create({
  screen: { flex: 1 }, content: { padding: 18, paddingBottom: 32 }, flex: { flex: 1 }, accountCard: { flexDirection: "row", alignItems: "center", gap: 14, backgroundColor: colors.surfaceRaised, borderRadius: 22, padding: 18 }, avatar: { width: 58, height: 58, borderRadius: 29, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, guest: { color: colors.text, fontSize: 18, fontWeight: "900" }, guestCopy: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  primaryButton: { backgroundColor: colors.primary, borderRadius: 18, padding: 17, alignItems: "center", marginTop: 14 }, editButton: { backgroundColor: colors.primary, borderRadius: 18, padding: 15, alignItems: "center", marginTop: 14 }, primaryText: { color: colors.white, fontSize: 14, fontWeight: "900" }, error: { color: "#ffaaa1", backgroundColor: "#3d2021", padding: 13, borderRadius: 14, marginTop: 12 },
  form: { gap: 10, backgroundColor: colors.surfaceRaised, borderRadius: 20, padding: 15, marginTop: 14 }, formTitle: { color: colors.text, fontWeight: "900", fontSize: 17 }, input: { height: 51, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, color: colors.text, borderRadius: 14, paddingHorizontal: 13 }, actions: { flexDirection: "row", gap: 10 }, cancelButton: { flex: 1, minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 15, alignItems: "center", justifyContent: "center" }, saveButton: { flex: 1, minHeight: 48, backgroundColor: colors.primary, borderRadius: 15, alignItems: "center", justifyContent: "center" },
  sectionTitle: { color: colors.text, fontSize: 19, fontWeight: "900", marginTop: 25, marginBottom: 12 }, menu: { gap: 9 }, menuItem: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 17, padding: 13 }, menuIcon: { width: 40, height: 40, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: "center", justifyContent: "center" }, menuTitle: { color: colors.text, fontSize: 14, fontWeight: "800" }, menuCopy: { color: colors.muted, fontSize: 10, lineHeight: 15, marginTop: 2 }, trustNote: { flexDirection: "row", gap: 10, backgroundColor: colors.primarySoft, borderRadius: 17, padding: 15, marginTop: 18 }, trustText: { flex: 1, color: "#bcebdd", fontSize: 11, lineHeight: 17 }
});
