import type { ImagePickerAsset } from "expo-image-picker";
import { supabase } from "./marketplace";
async function current() { if (!supabase) throw new Error("Hazi mobile is not connected to Supabase."); const r = await supabase.auth.getUser(); if (r.error || !r.data.user) throw new Error("Sign in again to continue."); return r.data.user; }
async function upload(asset: ImagePickerAsset, userId: string, suffix: string) { if (!asset.mimeType || !["image/jpeg", "image/png", "image/webp"].includes(asset.mimeType) || (asset.fileSize ?? 0) > 10 * 1024 * 1024) throw new Error("Use a JPEG, PNG, or WebP image no larger than 10MB."); const path = `${userId}/${Date.now()}-${suffix}-${asset.fileName || "image.jpg"}`; const blob = await (await fetch(asset.uri)).blob(); const r = await supabase!.storage.from("verification-documents").upload(path, blob, { contentType: asset.mimeType }); if (r.error) throw new Error(r.error.message); return path; }
export async function submitVerification(document: ImagePickerAsset, selfie: ImagePickerAsset, notes: string) { const user = await current(); const documentPath = await upload(document, user.id, "document"); const selfiePath = await upload(selfie, user.id, "liveness"); const r = await supabase!.from("verification_records").insert({ user_id: user.id, document_type: "government_id", status: "pending", notes: notes.trim() || null, document_url: documentPath, document_name: document.fileName || "identity-document", liveness_url: selfiePath, liveness_name: selfie.fileName || "liveness-selfie", liveness_required: true, liveness_status: "pending", face_match_status: "pending" }); if (r.error) throw new Error(r.error.message); }
export async function submitSupport(category: string, subject: string, description: string) { const user = await current(); if (!category || !subject.trim() || !description.trim()) throw new Error("Complete category, subject, and description."); const urgent = category === "appeal"; const high = ["agent_application", "escrow", "safety"].includes(category); const r = await supabase!.from("support_tickets").insert({ user_id: user.id, category, subject: subject.trim(), description: description.trim(), priority: urgent ? "urgent" : high ? "high" : "normal", escalation_level: urgent || category === "agent_application" ? 1 : 0, escalation_reason: urgent ? "Suspension appeal requires admin review." : category === "agent_application" ? "Agent application requires admin review." : null, escalated_at: urgent || category === "agent_application" ? new Date().toISOString() : null }); if (r.error) throw new Error(r.error.message); }
export async function manageListing(id: string, status: string) { const user = await current(); if (status === "active") { const r = await supabase!.from("auctions").update({ status: "paused" }).eq("id", id).eq("seller_id", user.id).eq("status", "active"); if (r.error) throw new Error(r.error.message); return; } if (status === "draft") { const r = await supabase!.from("auctions").update({ status: "active" }).eq("id", id).eq("seller_id", user.id).eq("status", "draft"); if (r.error) throw new Error(r.error.message); return; } const { data: auction } = await supabase!.from("auctions").select("seller_price").eq("id", id).eq("seller_id", user.id).maybeSingle(); if (!auction || !["paused", "closed", "expired"].includes(status)) throw new Error("This listing cannot be relisted."); const r = await supabase!.from("auctions").update({ status: "active", accepted_bid_id: null, current_bid: Math.round(Number(auction.seller_price) * 0.5), ends_at: new Date(Date.now() + 72 * 3600000).toISOString() }).eq("id", id).eq("seller_id", user.id).eq("status", status); if (r.error) throw new Error(r.error.message); await supabase!.from("bids").update({ status: "rejected" }).eq("auction_id", id).eq("status", "pending"); }
export async function claimAgentLead(id: string) { await current(); const r = await supabase!.rpc("claim_agent_lead_as_job", { p_lead_id: id }); if (r.error) throw new Error(r.error.message); }
export async function updateAssignedLead(id: string, status: "contacted" | "closed") { const user = await current(); const r = await supabase!.from("agent_leads").update({ status }).eq("id", id).eq("assigned_agent_id", user.id); if (r.error) throw new Error(r.error.message); }
export async function updateAgentJob(id: string, status: "assigned" | "scheduled" | "in_progress" | "inventory_ready" | "completed" | "cancelled") { await current(); const r = await supabase!.rpc("update_agent_job_status", { p_job_id: id, p_status: status, p_commission: null, p_notes: null }); if (r.error) throw new Error(r.error.message); }
