import { supabase } from "./marketplace";
export type ActivityKind = "bids" | "orders" | "notifications" | "disputes";
export type ActivityRow = { id: string; title: string; detail: string; status: string; amount?: number; isBuyer?: boolean; isSeller?: boolean };
export type TransactionDetail = ActivityRow & { buyerId: string; sellerId: string; sellerDeliveryStartedAt: string | null; messages: { id: string; body: string; senderId: string }[] };
async function user() { if (!supabase) throw new Error("Hazi mobile is not connected to Supabase."); const result = await supabase.auth.getUser(); if (result.error || !result.data.user) throw new Error("Sign in again to continue."); return result.data.user; }
function title(value: unknown) { const row = Array.isArray(value) ? value[0] : value; return row && typeof row === "object" && "title" in row ? String(row.title) : "Hazi auction"; }
export async function loadActivity(kind: ActivityKind): Promise<ActivityRow[]> { const current = await user(); if (kind === "bids") { const r = await supabase!.from("bids").select("id,amount,status,created_at,auctions(title)").eq("bidder_id", current.id).order("created_at", { ascending: false }); if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: title(x.auctions), detail: new Date(x.created_at).toLocaleDateString("en-NG"), status: x.status, amount: Number(x.amount) })); } if (kind === "notifications") { const r = await supabase!.from("notifications").select("id,title,body,read_at").eq("user_id", current.id).order("created_at", { ascending: false }).limit(50); if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: x.title, detail: x.body, status: x.read_at ? "read" : "new" })); } let q = supabase!.from("transactions").select("id,amount,status,buyer_id,seller_id,auctions(title)").or(`buyer_id.eq.${current.id},seller_id.eq.${current.id}`).order("created_at", { ascending: false }); if (kind === "disputes") q = q.eq("status", "disputed"); const r = await q; if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: title(x.auctions), detail: x.buyer_id === current.id ? "Purchase" : "Sale", status: x.status, amount: Number(x.amount), isBuyer: x.buyer_id === current.id, isSeller: x.seller_id === current.id })); }
export async function loadTransaction(id: string): Promise<TransactionDetail> { const current = await user(); const [r, m] = await Promise.all([supabase!.from("transactions").select("id,amount,status,buyer_id,seller_id,seller_delivery_started_at,auctions(title)").eq("id", id).maybeSingle(), supabase!.from("transaction_messages").select("id,body,sender_id").eq("transaction_id", id).order("created_at")]); if (r.error || !r.data || ![r.data.buyer_id, r.data.seller_id].includes(current.id)) throw new Error("Transaction not found."); if (m.error) throw m.error; const x = r.data; return { id: x.id, title: title(x.auctions), detail: x.buyer_id === current.id ? "Purchase" : "Sale", status: x.status, amount: Number(x.amount), isBuyer: x.buyer_id === current.id, isSeller: x.seller_id === current.id, buyerId: x.buyer_id, sellerId: x.seller_id, sellerDeliveryStartedAt: x.seller_delivery_started_at, messages: (m.data ?? []).map((v) => ({ id: v.id, body: v.body, senderId: v.sender_id })) }; }
export async function payWallet(id: string) { await user(); const r = await supabase!.rpc("pay_transaction_from_wallet", { p_transaction_id: id }); if (r.error) throw new Error(r.error.message); }
export async function deliver(id: string) { const current = await user(); const r = await supabase!.from("transactions").update({ seller_delivery_started_at: new Date().toISOString() }).eq("id", id).eq("seller_id", current.id).eq("status", "paid").is("seller_delivery_started_at", null).select("id").maybeSingle(); if (r.error || !r.data) throw new Error(r.error?.message || "Only the seller can start delivery after payment."); }
export async function receive(id: string) { const current = await user(); const r = await supabase!.from("transactions").update({ buyer_received_at: new Date().toISOString() }).eq("id", id).eq("buyer_id", current.id).eq("status", "paid").select("id").maybeSingle(); if (r.error || !r.data) throw new Error(r.error?.message || "Only the buyer can confirm receipt after payment."); const next = await supabase!.rpc("update_transaction_status", { p_transaction_id: id, p_next_status: "released" }); if (next.error) throw new Error(next.error.message); }
export async function dispute(id: string) { await user(); const r = await supabase!.rpc("update_transaction_status", { p_transaction_id: id, p_next_status: "disputed" }); if (r.error) throw new Error(r.error.message); }
export async function sendMessage(id: string, body: string) { const current = await user(); if (!body.trim()) throw new Error("Message cannot be empty."); const t = await supabase!.from("transactions").select("buyer_id,seller_id").eq("id", id).maybeSingle(); if (!t.data || ![t.data.buyer_id, t.data.seller_id].includes(current.id)) throw new Error("Only transaction participants can send messages."); const r = await supabase!.from("transaction_messages").insert({ transaction_id: id, sender_id: current.id, body: body.trim() }); if (r.error) throw new Error(r.error.message); }
export async function readNotification(id: string) { const current = await user(); const r = await supabase!.from("notifications").update({ read_at: new Date().toISOString() }).eq("id", id).eq("user_id", current.id); if (r.error) throw new Error(r.error.message); }
export async function submitEvidence(id: string, notes: string) { const current = await user(); if (!notes.trim()) throw new Error("Add an evidence note."); const t = await supabase!.from("transactions").select("buyer_id,seller_id,status").eq("id", id).maybeSingle(); if (!t.data || ![t.data.buyer_id, t.data.seller_id].includes(current.id) || t.data.status !== "disputed") throw new Error("Evidence can only be added by a participant to a disputed transaction."); const r = await supabase!.from("dispute_evidence").insert({ transaction_id: id, submitted_by: current.id, evidence_type: "note", notes: notes.trim() }); if (r.error) throw new Error(r.error.message); }
