import { supabase } from "./marketplace";
import type { ImagePickerAsset } from "expo-image-picker";
export type ActivityKind = "bids" | "orders" | "notifications" | "disputes";
export type ActivityRow = { id: string; title: string; detail: string; status: string; amount?: number; isBuyer?: boolean; isSeller?: boolean };
export type TransactionDetail = ActivityRow & { buyerId: string; sellerId: string; sellerDeliveryStartedAt: string | null; messages: { id: string; body: string; senderId: string }[] };
async function user() { if (!supabase) throw new Error("Hazi mobile is not connected to Supabase."); const result = await supabase.auth.getUser(); if (result.error || !result.data.user) throw new Error("Sign in again to continue."); return result.data.user; }
function title(value: unknown) { const row = Array.isArray(value) ? value[0] : value; return row && typeof row === "object" && "title" in row ? String(row.title) : "Hazi auction"; }
export async function loadActivity(kind: ActivityKind): Promise<ActivityRow[]> { const current = await user(); if (kind === "bids") { const r = await supabase!.from("bids").select("id,amount,status,created_at,auctions(title)").eq("bidder_id", current.id).order("created_at", { ascending: false }); if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: title(x.auctions), detail: new Date(x.created_at).toLocaleDateString("en-NG"), status: x.status, amount: Number(x.amount) })); } if (kind === "notifications") { const r = await supabase!.from("notifications").select("id,title,body,read_at").eq("user_id", current.id).order("created_at", { ascending: false }).limit(50); if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: x.title, detail: x.body, status: x.read_at ? "read" : "new" })); } let q = supabase!.from("transactions").select("id,amount,status,buyer_id,seller_id,auctions(title)").or(`buyer_id.eq.${current.id},seller_id.eq.${current.id}`).order("created_at", { ascending: false }); if (kind === "disputes") q = q.eq("status", "disputed"); const r = await q; if (r.error) throw r.error; return (r.data ?? []).map((x) => ({ id: x.id, title: title(x.auctions), detail: x.buyer_id === current.id ? "Purchase" : "Sale", status: x.status, amount: Number(x.amount), isBuyer: x.buyer_id === current.id, isSeller: x.seller_id === current.id })); }
export async function loadTransaction(id: string): Promise<TransactionDetail> { const current = await user(); const [r, m] = await Promise.all([supabase!.from("transactions").select("id,amount,status,buyer_id,seller_id,seller_delivery_started_at,auctions(title)").eq("id", id).maybeSingle(), supabase!.from("transaction_messages").select("id,body,sender_id").eq("transaction_id", id).order("created_at")]); if (r.error || !r.data || ![r.data.buyer_id, r.data.seller_id].includes(current.id)) throw new Error("Transaction not found."); if (m.error) throw m.error; const x = r.data; return { id: x.id, title: title(x.auctions), detail: x.buyer_id === current.id ? "Purchase" : "Sale", status: x.status, amount: Number(x.amount), isBuyer: x.buyer_id === current.id, isSeller: x.seller_id === current.id, buyerId: x.buyer_id, sellerId: x.seller_id, sellerDeliveryStartedAt: x.seller_delivery_started_at, messages: (m.data ?? []).map((v) => ({ id: v.id, body: v.body, senderId: v.sender_id })) }; }
export async function payWallet(id: string) { await user(); const r = await supabase!.rpc("pay_transaction_from_wallet", { p_transaction_id: id }); if (r.error) throw new Error(r.error.message); }
export async function deliver(id: string) { const current = await user(); const r = await supabase!.from("transactions").update({ seller_delivery_started_at: new Date().toISOString() }).eq("id", id).eq("seller_id", current.id).eq("status", "paid").is("seller_delivery_started_at", null).select("id").maybeSingle(); if (r.error || !r.data) throw new Error(r.error?.message || "Only the seller can start delivery after payment."); }
export async function receive(id: string) { const current = await user(); const r = await supabase!.from("transactions").update({ buyer_received_at: new Date().toISOString() }).eq("id", id).eq("buyer_id", current.id).eq("status", "paid").select("id").maybeSingle(); if (r.error || !r.data) throw new Error(r.error?.message || "Only the buyer can confirm receipt after payment."); const next = await supabase!.rpc("update_transaction_status", { p_transaction_id: id, p_next_status: "released" }); if (next.error) throw new Error(next.error.message); }
export async function dispute(id: string) { await user(); const r = await supabase!.rpc("update_transaction_status", { p_transaction_id: id, p_next_status: "disputed" }); if (r.error) throw new Error(r.error.message); }
export async function sendMessage(id: string, body: string) { const current = await user(); if (!body.trim()) throw new Error("Message cannot be empty."); const t = await supabase!.from("transactions").select("buyer_id,seller_id").eq("id", id).maybeSingle(); if (!t.data || ![t.data.buyer_id, t.data.seller_id].includes(current.id)) throw new Error("Only transaction participants can send messages."); const r = await supabase!.from("transaction_messages").insert({ transaction_id: id, sender_id: current.id, body: body.trim() }); if (r.error) throw new Error(r.error.message); }
export async function readNotification(id: string) { const current = await user(); const r = await supabase!.from("notifications").update({ read_at: new Date().toISOString() }).eq("id", id).eq("user_id", current.id); if (r.error) throw new Error(r.error.message); }
export async function submitEvidence(id: string, notes: string, asset?: ImagePickerAsset | null) { const current = await user(); if (!notes.trim() && !asset) throw new Error("Add a note or choose evidence."); const t = await supabase!.from("transactions").select("buyer_id,seller_id,status").eq("id", id).maybeSingle(); if (!t.data || ![t.data.buyer_id, t.data.seller_id].includes(current.id) || t.data.status !== "disputed") throw new Error("Evidence can only be added by a participant to a disputed transaction."); let fileUrl: string | null = null; let fileName: string | null = null; if (asset) { if (!asset.mimeType || !["image/jpeg", "image/png", "image/webp"].includes(asset.mimeType) || (asset.fileSize ?? 0) > 10 * 1024 * 1024) throw new Error("Evidence must be a JPEG, PNG, or WebP image no larger than 10MB."); fileName = asset.fileName || "evidence.jpg"; fileUrl = `${current.id}/${id}/${Date.now()}-${fileName.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const blob = await (await fetch(asset.uri)).blob(); const upload = await supabase!.storage.from("dispute-evidence").upload(fileUrl, blob, { contentType: asset.mimeType, upsert: false }); if (upload.error) throw new Error(upload.error.message); } const r = await supabase!.from("dispute_evidence").insert({ transaction_id: id, submitted_by: current.id, evidence_type: fileUrl ? "file" : "note", file_url: fileUrl, file_name: fileName, notes: notes.trim() || null }); if (r.error) throw new Error(r.error.message); }
export async function submitPaymentProof(id: string, reference: string, asset: ImagePickerAsset) { const current = await user(); if (!asset.mimeType || !["image/jpeg", "image/png", "image/webp"].includes(asset.mimeType) || (asset.fileSize ?? 0) > 10 * 1024 * 1024) throw new Error("Payment proof must be a JPEG, PNG, or WebP image no larger than 10MB."); const transaction = await supabase!.from("transactions").select("buyer_id,amount,status").eq("id", id).maybeSingle(); if (!transaction.data || transaction.data.buyer_id !== current.id) throw new Error("Only the buyer can submit payment proof."); if (transaction.data.status !== "escrow_pending") throw new Error("Payment proof can only be submitted while escrow is pending."); const existing = await supabase!.from("transaction_payments").select("status").eq("transaction_id", id).in("status", ["pending", "verified"]).maybeSingle(); if (existing.data) throw new Error(existing.data.status === "verified" ? "This payment is already verified." : "A payment proof is already waiting for review."); const fileName = asset.fileName || "payment-proof.jpg"; const fileUrl = `${current.id}/${id}/${Date.now()}-${fileName.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const blob = await (await fetch(asset.uri)).blob(); const upload = await supabase!.storage.from("payment-proofs").upload(fileUrl, blob, { contentType: asset.mimeType, upsert: false }); if (upload.error) throw new Error(upload.error.message); const inserted = await supabase!.from("transaction_payments").insert({ transaction_id: id, payer_id: current.id, amount: transaction.data.amount, method: "bank_transfer", reference: reference.trim() || null, proof_url: fileUrl, proof_name: fileName, status: "pending" }); if (inserted.error) throw new Error(inserted.error.message); }
